### ISSUE TITLE
Contact Us form

### ISSUE THREAD

**Issue by ML72** [The-Mu-Foundation/Mutorials#116]
@Ved

**Comment by PerpetualCreativity** [comment]
Do we need a Contact Us button on `/homepage`?

**Comment by yadavta** [comment]
I'll make one, what page should it be on? I was thinking `/contact`

**Comment by PerpetualCreativity** [comment]
Sure. Original reason for a contact form was for people to report problems on questions (misspellings, incorrect answer etc) so link to it from there as well.

**Comment by yadavta** [comment]
Should I do it in Bootstrap 4 or 5?

**Comment by PerpetualCreativity** [comment]
Go with bootstrap 4 for now, we'll switch everything to bootstrap 5 later. (So that we don't have any conflicts between versions 4 and 5).
