### ISSUE TITLE
Make "Report this question:" Functional

### ISSUE THREAD

**Issue by PreisdentPlant** [The-Mu-Foundation/Mutorials#222]
Actually let users submit issues with the problems instead of messaging the admins

**Comment by ML72** [comment]
Agreed. What if we made a webhook post it in our discord server or smth?

**Comment by PreisdentPlant** [comment]
Discord server works, but a list/table would be a lot easier to use, at least in my opinion.

**Comment by ML72** [comment]
Ok, got it. TBH we might as well as just create a new database collection for reported questions. This also goes hand in hand with an "edit question" form

**Comment by PerpetualCreativity** [comment]
Relevant: #192

**Comment by ML72** [comment]
@PerpetualCreativity can this be closed?
