### ISSUE TITLE
Update Preferences Button also tries to update Profile

### ISSUE THREAD

**Issue by PresidentPlant** [The-Mu-Foundation/Mutorials#233]
When the update preferences button is clicked, the site reloads and shows the following messages.

![image](https://user-images.githubusercontent.com/57729743/95277825-b0854d80-0889-11eb-8a0c-32c5e5761c68.png)

**Comment by PresidentPlant** [comment]
Probably fixed it w the pull request. Waiting for someone credible to accept the PR / close the issue

**Comment by ML72** [comment]
Yes, fixed in #258
