### ISSUE TITLE
"Username already taken" flash doesn't work.

### ISSUE THREAD

**Issue by PerpetualCreativity** [The-Mu-Foundation/Mutorials#236]

**Comment by PresidentPlant** [comment]
Is it the flash that doesn't work, or the detection? Because I just made 3 accounts w the same username and overwrites the old account w the same username.

Also, maybe change `user.username` to 'user.email` and 'user.ign` to 'user.username'? Seems it'll make debugging less harder.

**Comment by PerpetualCreativity** [comment]
I've tried to reproduce this bug with multiple different usernames and emails. I'm going to close this; if someone has a test case that works, please reopen this issue.
