### ISSUE TITLE
Multiple dailies in a day

### ISSUE THREAD

**Issue by ML72** [The-Mu-Foundation/Mutorials#239]
Unreproducible bug, but its very annoying D:<

**Comment by ML72** [comment]
Hard to reproduce

**Comment by ML72** [comment]
Currently fixed with the help of a few console.log statements, but that seems very 😬

**Comment by PresidentPlant** [comment]
If there hasn't been any more problems after #262, I think we could either close this, or change the schema to use MongoDB's local currentDate. Hopefully.

**Comment by ML72** [comment]
Mhmm, looks fixed thx to @PresidentPlant
