### ISSUE TITLE
Make 'Current Password' box actually check for password

### ISSUE THREAD

**Issue by PresidentPlant** [The-Mu-Foundation/Mutorials#255]
![image](https://user-images.githubusercontent.com/57729743/95701498-b6fa3780-0c84-11eb-8a7c-f5261df500c7.png)

The current password box is just there for looks, without providing any security functionality whatsoever. Might work as a placebo, but just to be safe, let's actually check the current password.

**Comment by ML72** [comment]
oops closed wrong issue this was done in #315
