### ISSUE TITLE
"Enter PW to confirm" for delete account

### ISSUE THREAD

**Issue by ML72** [The-Mu-Foundation/Mutorials#256]
Similar to issue #255 - same person can handle both

**Comment by ML72** [comment]
Btw the modal looks kinda out of place from other modals on the site. Might change some styling.

Also food for thought: "Delete Account" -> "DANGER ZONE" (cringe)

**Comment by ML72** [comment]
ethan did this #315

**Comment by ML72** [comment]
sorry my bad, this isnt done yet

**Comment by bulkypanda** [comment]
@womogenes should be fixed, confirm and merge
