### ISSUE TITLE
Add new chem concept tags

### ISSUE THREAD

**Issue by ML72** [The-Mu-Foundation/Mutorials#261]
POL - polarity
ENEG - electronegativity
COVB - covalent bonding
IONB - ionic bonding
MGEO - molecular geometry
CONV - conversions
[may be edited to add more]

**Comment by l1dub** [comment]
EMP - empirical formulas
LIMIT - Limiting Reactant

**Comment by ML72** [comment]
Added in #265

**Comment by l1dub** [comment]
BOYLE | Boyle's Law
GAYL | Gay-Lussac's Law
CHAR | Charles's Law

**Comment by l1dub** [comment]
AVO | Avogadro's Law

**Comment by ML72** [comment]
Being done in new commit
