### ISSUE TITLE
Dark Mode on Leaderboard Page

### ISSUE THREAD

**Issue by yadavta** [The-Mu-Foundation/Mutorials#343]
The dark blue text on the Leaderboard page isn't the most readable, especially if your display is in a low-blue light / night mode of sorts. The bright yellow color of first place is also rather bright for a dark mode, so I think it might be benefical to find a more dull shade of yellow; that should also help make the white text on the yellow rectangles for 1st place more readable too!

![image](https://user-images.githubusercontent.com/20195205/106804582-700cc500-661a-11eb-94b6-a7dc20964901.png)

**Comment by aradhana72** [comment]
I wish to fix this bug. Will surely get through the solution soon.

**Comment by ML72** [comment]
> I wish to fix this bug. Will surely get through the solution soon.

@aradhana72 Sure, that would be great! :)
(and if by any chance, you want to talk to us about more bugs/fixes/Mutorials coding techniques, feel free to join our discord server at https://discord.com/invite/ccbZu4q !)

**Comment by aradhana72** [comment]
Yeah sure !!! Would be awesome to learn from your community!!!

**Comment by bulkypanda** [comment]
commit dn7a94c fixes
