### ISSUE TITLE
Require null checks on profile update in 'settings'

### ISSUE THREAD

**Issue by nicktolhurst** [The-Mu-Foundation/Mutorials#385]
I came across this looking at another bug! 

On the `/settings` page, If any of the 4 form fields are left blank, and the form is submitted, an error is thrown. This seems to be because we can't use `filter.clean()` on a null string. 

```
TypeError: Cannot read property '0' of null
at Filter.clean (Z:\Contributions\TheMuFoundation\Mutorials\node_modules\bad-words\lib\badwords.js:58:41)
    at Z:\Contributions\TheMuFoundation\Mutorials\routes\settings.js:41:40
```

**Comment by PerpetualCreativity** [comment]
Good catch.

**Comment by PerpetualCreativity** [comment]
Do you want to make a PR for this? If not I can push a fix soon.
