### ISSUE TITLE
Add eslint and an extendable configuration for PR reviews

### ISSUE THREAD

**Issue by nicktolhurst** [The-Mu-Foundation/Mutorials#390]
Have you considered adding `eslint` for some quick styling feedback on PRs? 

It would also pave a way for adding unit/integration/e2e tests in the future.

Let me know what you think, I could throw together a PR this evening (GMT).

**Comment by PerpetualCreativity** [comment]
Hi Nick!

Adding eslint would be great, PR welcome :)

When you add it, could you please edit `.eslintrc` to better conform to our current style guidelines? (You can find them in `CONTRIBUTING.md`. If you come across something problematic there just drop a comment on this issue and we can talk about it.)

**Comment by nicktolhurst** [comment]
I think it would be best to avoid a mass refactor by just adding the linting framework and workflow in this PR, and then to tackle the rules in separate PRs. 

Breaking it down in to smaller PRs will reduce risk and provide benefit much earlier on.

I'm picking this up now.
