### ISSUE TITLE
Allow mutorials.org base directory

### ISSUE THREAD

**Issue by dannyridel** [The-Mu-Foundation/Mutorials#450]
instead of only allowing www.mutorials.org, allow mutorials.org access.

**Comment by bulkypanda** [comment]
https://www.mutorials.org & https://mutorials.org both work now.

**Comment by dannyridel** [comment]
@bulkypanda check certificate stuff

**Comment by bulkypanda** [comment]
@dannyridel try on personal pc. certificate might just be an issue with bsd
