### ISSUE TITLE
Only getting competition problems in Bio mode

### ISSUE THREAD

**Issue by womogenes** [The-Mu-Foundation/Mutorials#503]
When user rating ~3200, they're only getting competition problems in Bio mode.

**Comment by TheFalloutOf76** [comment]
have you looked in the db and confirmed that there are actually non competition problems at that rating in db?

**Comment by womogenes** [comment]
There are. We suspect it's some combination of database/code issues, and will continue to look into it further.

**Comment by TheFalloutOf76** [comment]
really? i looked into it and found only 1/25 biology questions with a rating above 2500 were non-competition

**Comment by TheFalloutOf76** [comment]
out of the questions above 2000, 1/50 biology questions are original

**Comment by TheFalloutOf76** [comment]
because there are only 1 original question near their rating, they would almost never get anything other than competition problems

**Comment by TheFalloutOf76** [comment]
ah i see its a database formatting error, i can fix it

**Comment by TheFalloutOf76** [comment]
@womogenes fixed, go try it
