### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by PerpetualCreativity** [The-Mu-Foundation/Mutorials#84]
Let's not use Google Analytics as it will be blocked by adblockers.

**Comment by oupadhyay** [comment]
Maybe use:
 - https://www.freecodecamp.org/news/save-your-analytics-from-content-blockers-7ee08c6ec7ee/

**Comment by ML72** [comment]
Will do very soon. Assuming these are user analytics

**Comment by PerpetualCreativity** [comment]
negative. this is site analytics (how many people visit our website, from where do they come (google, somewhere else), avg time on site, etc.)
